import React, { useState } from 'react';

export const MARKET_DATA = [
  {
    id: 'btcusdt',
    name: 'BTC/USDT',
    base_unit: 'btc',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 5,
    price_precision: 0,
    min_price: '1',
    max_price: '100000',
    min_amount: '0.00005',
    position: 1,
    filters: [],
  },
  {
    id: 'btcinr',
    name: 'BTC/INR',
    base_unit: 'btc',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 5,
    price_precision: 0,
    min_price: '100',
    max_price: '10000000',
    min_amount: '0.00005',
    position: 2,
    filters: [],
  },
  {
    id: 'ethusdt',
    name: 'ETH/USDT',
    base_unit: 'eth',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 4,
    price_precision: 2,
    min_price: '1',
    max_price: '10000',
    min_amount: '0.001',
    position: 4,
    filters: [],
  },
  {
    id: 'ethinr',
    name: 'ETH/INR',
    base_unit: 'eth',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 4,
    price_precision: 0,
    min_price: '100',
    max_price: '10000000',
    min_amount: '0.001',
    position: 5,
    filters: [],
  },
  {
    id: 'ethbtc',
    name: 'ETH/BTC',
    base_unit: 'eth',
    quote_unit: 'btc',
    state: 'enabled',
    amount_precision: 4,
    price_precision: 6,
    min_price: '0.00001',
    max_price: '2',
    min_amount: '0.001',
    position: 6,
    filters: [],
  },
  {
    id: 'ltcusdt',
    name: 'LTC/USDT',
    base_unit: 'ltc',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 2,
    min_price: '30',
    max_price: '825',
    min_amount: '0.01',
    position: 7,
    filters: [],
  },
  {
    id: 'usdtinr',
    name: 'USDT/INR',
    base_unit: 'usdt',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '50',
    max_price: '100',
    min_amount: '1.5',
    position: 8,
    filters: [],
  },
  {
    id: 'ltcinr',
    name: 'LTC/INR',
    base_unit: 'ltc',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 2,
    min_price: '2000',
    max_price: '100000',
    min_amount: '0.01',
    position: 9,
    filters: [],
  },
  {
    id: 'shibinr',
    name: 'SHIB/INR',
    base_unit: 'shib',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 0,
    price_precision: 6,
    min_price: '0.00001',
    max_price: '0.01',
    min_amount: '50000',
    position: 10,
    filters: [],
  },
  {
    id: 'shibusdt',
    name: 'SHIB/USDT',
    base_unit: 'shib',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 0,
    price_precision: 8,
    min_price: '0.0000001',
    max_price: '0.001',
    min_amount: '50000',
    position: 11,
    filters: [],
  },
  {
    id: 'dogeinr',
    name: 'DOGE/INR',
    base_unit: 'doge',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 0,
    price_precision: 4,
    min_price: '1',
    max_price: '200',
    min_amount: '10',
    position: 12,
    filters: [],
  },
  {
    id: 'dogeusdt',
    name: 'DOGE/USDT',
    base_unit: 'doge',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 0,
    price_precision: 7,
    min_price: '0.01',
    max_price: '3',
    min_amount: '10',
    position: 13,
    filters: [],
  },
  {
    id: 'solinr',
    name: 'SOL/INR',
    base_unit: 'sol',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 2,
    min_price: '1200',
    max_price: '100000',
    min_amount: '0.015',
    position: 14,
    filters: [],
  },
  {
    id: 'solusdt',
    name: 'SOL/USDT',
    base_unit: 'sol',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 3,
    min_price: '20',
    max_price: '1500',
    min_amount: '0.015',
    position: 15,
    filters: [],
  },
  {
    id: 'adainr',
    name: 'ADA/INR',
    base_unit: 'ada',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 4,
    min_price: '50',
    max_price: '1000',
    min_amount: '1',
    position: 16,
    filters: [],
  },
  {
    id: 'adausdt',
    name: 'ADA/USDT',
    base_unit: 'ada',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 5,
    min_price: '0.5',
    max_price: '15',
    min_amount: '1',
    position: 17,
    filters: [],
  },
  {
    id: 'adabtc',
    name: 'ADA/BTC',
    base_unit: 'ada',
    quote_unit: 'btc',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 8,
    min_price: '0.000003',
    max_price: '0.0005',
    min_amount: '10',
    position: 18,
    filters: [],
  },
  {
    id: 'ltcbtc',
    name: 'LTC/BTC',
    base_unit: 'ltc',
    quote_unit: 'btc',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 6,
    min_price: '0.000726',
    max_price: '0.018155',
    min_amount: '0.01',
    position: 19,
    filters: [],
  },
  {
    id: 'xrpinr',
    name: 'XRP/INR',
    base_unit: 'xrp',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 3,
    min_price: '20',
    max_price: '400',
    min_amount: '2',
    position: 20,
    filters: [],
  },
  {
    id: 'xrpusdt',
    name: 'XRP/USDT',
    base_unit: 'xrp',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 4,
    min_price: '0.25',
    max_price: '5',
    min_amount: '4',
    position: 21,
    filters: [],
  },
  {
    id: 'xrpbtc',
    name: 'XRP/BTC',
    base_unit: 'xrp',
    quote_unit: 'btc',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 8,
    min_price: '0.000009',
    max_price: '0.000093',
    min_amount: '8',
    position: 22,
    filters: [],
  },
  {
    id: 'trxinr',
    name: 'TRX/INR',
    base_unit: 'trx',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 0,
    price_precision: 3,
    min_price: '1',
    max_price: '40',
    min_amount: '20',
    position: 23,
    filters: [],
  },
  {
    id: 'trxusdt',
    name: 'TRX/USDT',
    base_unit: 'trx',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 0,
    price_precision: 5,
    min_price: '0.02',
    max_price: '1',
    min_amount: '40',
    position: 24,
    filters: [],
  },
  {
    id: 'trxbtc',
    name: 'TRX/BTC',
    base_unit: 'trx',
    quote_unit: 'btc',
    state: 'hidden',
    amount_precision: 0,
    price_precision: 8,
    min_price: '0.0000003',
    max_price: '0.000008',
    min_amount: '100',
    position: 25,
    filters: [],
  },
  {
    id: 'dotinr',
    name: 'DOT/INR',
    base_unit: 'dot',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '1000',
    max_price: '20000',
    min_amount: '0.05',
    position: 26,
    filters: [],
  },
  {
    id: 'dotusdt',
    name: 'DOT/USDT',
    base_unit: 'dot',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '10',
    max_price: '200',
    min_amount: '0.1',
    position: 27,
    filters: [],
  },
  {
    id: 'lunainr',
    name: 'LUNA/INR',
    base_unit: 'luna',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 0,
    min_price: '500',
    max_price: '15000',
    min_amount: '0.06',
    position: 28,
    filters: [],
  },
  {
    id: 'lunausdt',
    name: 'LUNA/USDT',
    base_unit: 'luna',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '6',
    max_price: '180',
    min_amount: '0.1',
    position: 29,
    filters: [],
  },
  {
    id: 'xlminr',
    name: 'XLM/INR',
    base_unit: 'xlm',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 3,
    min_price: '5',
    max_price: '150',
    min_amount: '6',
    position: 30,
    filters: [],
  },
  {
    id: 'xlmusdt',
    name: 'XLM/USDT',
    base_unit: 'xlm',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 4,
    min_price: '0.08',
    max_price: '2',
    min_amount: '10',
    position: 31,
    filters: [],
  },
  {
    id: 'bnbinr',
    name: 'BNB/INR',
    base_unit: 'bnb',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 0,
    min_price: '10000',
    max_price: '250000',
    min_amount: '0.005',
    position: 32,
    filters: [],
  },
  {
    id: 'bnbusdt',
    name: 'BNB/USDT',
    base_unit: 'bnb',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 2,
    min_price: '100',
    max_price: '3000',
    min_amount: '0.008',
    position: 33,
    filters: [],
  },
  {
    id: 'bnbbtc',
    name: 'BNB/BTC',
    base_unit: 'bnb',
    quote_unit: 'btc',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 7,
    min_price: '0.0016',
    max_price: '0.05',
    min_amount: '0.025',
    position: 34,
    filters: [],
  },
  {
    id: 'busdinr',
    name: 'BUSD/INR',
    base_unit: 'busd',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '15',
    max_price: '400',
    min_amount: '2',
    position: 35,
    filters: [],
  },
  {
    id: 'busdusdt',
    name: 'BUSD/USDT',
    base_unit: 'busd',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 4,
    min_price: '0.2',
    max_price: '5',
    min_amount: '4',
    position: 36,
    filters: [],
  },
  {
    id: 'uniinr',
    name: 'UNI/INR',
    base_unit: 'uni',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 1,
    min_price: '500',
    max_price: '8000',
    min_amount: '0.08',
    position: 37,
    filters: [],
  },
  {
    id: 'uniusdt',
    name: 'UNI/USDT',
    base_unit: 'uni',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '6',
    max_price: '100',
    min_amount: '0.15',
    position: 38,
    filters: [],
  },
  {
    id: 'maticinr',
    name: 'MATIC/INR',
    base_unit: 'matic',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 2,
    min_price: '25',
    max_price: '600',
    min_amount: '1.5',
    position: 39,
    filters: [],
  },
  {
    id: 'maticusdt',
    name: 'MATIC/USDT',
    base_unit: 'matic',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 3,
    min_price: '0.3',
    max_price: '8',
    min_amount: '3',
    position: 40,
    filters: [],
  },
  {
    id: 'maticbtc',
    name: 'MATIC/BTC',
    base_unit: 'matic',
    quote_unit: 'btc',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 8,
    min_price: '0.000005',
    max_price: '0.00012',
    min_amount: '8',
    position: 41,
    filters: [],
  },
  {
    id: 'fttinr',
    name: 'FTT/INR',
    base_unit: 'ftt',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 0,
    min_price: '800',
    max_price: '22000',
    min_amount: '0.04',
    position: 42,
    filters: [],
  },
  {
    id: 'fttusdt',
    name: 'FTT/USDT',
    base_unit: 'ftt',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 3,
    min_price: '10',
    max_price: '300',
    min_amount: '0.07',
    position: 43,
    filters: [],
  },
  {
    id: 'avaxinr',
    name: 'AVAX/INR',
    base_unit: 'avax',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '1000',
    max_price: '25000',
    min_amount: '0.02',
    position: 45,
    filters: [],
  },
  {
    id: 'avaxusdt',
    name: 'AVAX/USDT',
    base_unit: 'avax',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '10',
    max_price: '500',
    min_amount: '0.05',
    position: 46,
    filters: [],
  },
  {
    id: 'nearinr',
    name: 'NEAR/INR',
    base_unit: 'near',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '100',
    max_price: '10000',
    min_amount: '0.06',
    position: 47,
    filters: [],
  },
  {
    id: 'nearusdt',
    name: 'NEAR/USDT',
    base_unit: 'near',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '1',
    max_price: '10',
    min_amount: '0.22',
    position: 48,
    filters: [],
  },
  {
    id: 'linkinr',
    name: 'LINK/INR',
    base_unit: 'link',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '150',
    max_price: '10000',
    min_amount: '0.06',
    position: 49,
    filters: [],
  },
  {
    id: 'linkusdt',
    name: 'LINK/USDT',
    base_unit: 'link',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '2',
    max_price: '200',
    min_amount: '0.18',
    position: 50,
    filters: [],
  },
  {
    id: 'algoinr',
    name: 'ALGO/INR',
    base_unit: 'algo',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '10',
    max_price: '1000',
    min_amount: '1',
    position: 51,
    filters: [],
  },
  {
    id: 'algousdt',
    name: 'ALGO/USDT',
    base_unit: 'algo',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 3,
    min_price: '0.1',
    max_price: '10',
    min_amount: '3',
    position: 52,
    filters: [],
  },
  {
    id: 'atominr',
    name: 'ATOM/INR',
    base_unit: 'atom',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 2,
    min_price: '300',
    max_price: '30000',
    min_amount: '0.1',
    position: 53,
    filters: [],
  },
  {
    id: 'atomusdt',
    name: 'ATOM/USDT',
    base_unit: 'atom',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '4',
    max_price: '400',
    min_amount: '0.1',
    position: 54,
    filters: [],
  },
  {
    id: 'ftminr',
    name: 'FTM/INR',
    base_unit: 'ftm',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 2,
    min_price: '20',
    max_price: '2000',
    min_amount: '0.4',
    position: 55,
    filters: [],
  },
  {
    id: 'ftmusdt',
    name: 'FTM/USDT',
    base_unit: 'ftm',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 4,
    min_price: '0.2',
    max_price: '20',
    min_amount: '1.3',
    position: 56,
    filters: [],
  },
  {
    id: 'bchinr',
    name: 'BCH/INR',
    base_unit: 'bch',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 0,
    min_price: '2400',
    max_price: '24000',
    min_amount: '0.004',
    position: 57,
    filters: [],
  },
  {
    id: 'bchusdt',
    name: 'BCH/USDT',
    base_unit: 'bch',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 2,
    min_price: '30',
    max_price: '3000',
    min_amount: '0.01',
    position: 58,
    filters: [],
  },
  {
    id: 'sandinr',
    name: 'SAND/INR',
    base_unit: 'sand',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 0,
    price_precision: 2,
    min_price: '35',
    max_price: '3500',
    min_amount: '1',
    position: 59,
    filters: [],
  },
  {
    id: 'sandusdt',
    name: 'SAND/USDT',
    base_unit: 'sand',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 0,
    price_precision: 3,
    min_price: '0.45',
    max_price: '45',
    min_amount: '1',
    position: 60,
    filters: [],
  },
  {
    id: 'manausdt',
    name: 'MANA/USDT',
    base_unit: 'mana',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 4,
    min_price: '0.3',
    max_price: '30',
    min_amount: '1.2',
    position: 61,
    filters: [],
  },
  {
    id: 'manainr',
    name: 'MANA/INR',
    base_unit: 'mana',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 3,
    min_price: '25',
    max_price: '2500',
    min_amount: '0.4',
    position: 62,
    filters: [],
  },
  {
    id: 'galainr',
    name: 'GALA/INR',
    base_unit: 'gala',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 0,
    price_precision: 3,
    min_price: '3',
    max_price: '300',
    min_amount: '4',
    position: 63,
    filters: [],
  },
  {
    id: 'galausdt',
    name: 'GALA/USDT',
    base_unit: 'gala',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 1,
    price_precision: 4,
    min_price: '0.036',
    max_price: '3.6',
    min_amount: '10',
    position: 64,
    filters: [],
  },
  {
    id: 'sushiinr',
    name: 'SUSHI/INR',
    base_unit: 'sushi',
    quote_unit: 'inr',
    state: 'enabled',
    amount_precision: 2,
    price_precision: 2,
    min_price: '37',
    max_price: '3700',
    min_amount: '0.3',
    position: 65,
    filters: [],
  },
  {
    id: 'sushiusdt',
    name: 'SUSHI/USDT',
    base_unit: 'sushi',
    quote_unit: 'usdt',
    state: 'enabled',
    amount_precision: 3,
    price_precision: 3,
    min_price: '0.5',
    max_price: '50',
    min_amount: '1',
    position: 66,
    filters: [],
  },
];

export const FEES = [
  {
    id: 'inr',
    status: 'enabled',
    name: 'Indian Rupee',
    description: null,
    options: {},
    homepage: null,
    price: '1.0',
    type: 'fiat',
    deposit_enabled: true,
    withdrawal_enabled: true,
    deposit_fee: '0.0',
    min_deposit_amount: '100.0',
    withdraw_fee: '10.0',
    min_withdraw_amount: '100.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 100,
    precision: 2,
    position: 1,
    icon_url:
      'https://01-public-assets.s3.ap-south-1.amazonaws.com/Inr_logo_40.png',
    blockchain_key: 'fiat',
    networks: [
      {
        id: 16,
        status: 'enabled',
        blockchain_key: 'fiat',
        currency_id: 'inr',
        deposit_enabled: true,
        withdrawal_enabled: true,
        deposit_fee: '0.0',
        min_deposit_amount: '100.0',
        withdraw_fee: '10.0',
        min_withdraw_amount: '200.0',
        base_factor: 100,
        description: null,
        warning: null,
        protocol: 'FIAT',
      },
    ],
  },
  {
    id: 'usdt',
    status: 'enabled',
    name: 'Tether',
    description: null,
    options: {
      erc20_contract_address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
    },
    homepage: null,
    price: '79.249811650777',
    explorer_transaction: 'https://etherscan.io/tx/#{txid}',
    explorer_address: 'https://etherscan.io/address/#{address}',
    type: 'coin',
    deposit_enabled: true,
    withdrawal_enabled: true,
    deposit_fee: '0.0',
    min_deposit_amount: '1.0',
    withdraw_fee: '20.0',
    min_withdraw_amount: '22.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000,
    precision: 2,
    position: 2,
    icon_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/825.png',
    min_confirmations: 6,
    blockchain_key: 'eth-mainnet',
    networks: [
      {
        id: 29,
        status: 'enabled',
        blockchain_key: 'eth-mainnet',
        currency_id: 'usdt',
        parent_id: 'eth',
        deposit_enabled: true,
        withdrawal_enabled: true,
        deposit_fee: '0.0',
        min_deposit_amount: '1.0',
        withdraw_fee: '20.0',
        min_withdraw_amount: '22.0',
        base_factor: 1000000,
        explorer_transaction: 'https://etherscan.io/tx/#{txid}',
        explorer_address: 'https://etherscan.io/address/#{address}',
        description: null,
        warning: null,
        protocol: 'Ethereum (ERC20)',
        min_confirmations: 6,
      },
      {
        id: 32,
        status: 'enabled',
        blockchain_key: 'tron-mainnet',
        currency_id: 'usdt',
        parent_id: 'trx',
        deposit_enabled: true,
        withdrawal_enabled: true,
        deposit_fee: '0.0',
        min_deposit_amount: '3.5',
        withdraw_fee: '1.0',
        min_withdraw_amount: '2.0',
        base_factor: 1000000,
        explorer_transaction: 'https://tronscan.org/#/transaction/#{txid}',
        explorer_address: 'https://tronscan.org/#/address/#{address}',
        description: '',
        warning: '',
        protocol: 'Tron (TRC20)',
        min_confirmations: 30,
      },
    ],
  },
  {
    id: 'btc',
    status: 'enabled',
    name: 'Bitcoin',
    description: null,
    options: {},
    homepage: null,
    price: '3102075.05300637',
    explorer_transaction: 'https://www.blockchain.com/btc/tx/#{txid}',
    explorer_address: 'https://www.blockchain.com/btc/address/#{address}',
    type: 'coin',
    deposit_enabled: true,
    withdrawal_enabled: true,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0002',
    withdraw_fee: '0.0005',
    min_withdraw_amount: '0.0006',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 100000000,
    precision: 6,
    position: 3,
    icon_url:
      'https://assets.coingecko.com/coins/images/1/small/bitcoin.png?1547033579',
    min_confirmations: 3,
    blockchain_key: 'btc-electrum',
    networks: [
      {
        id: 7,
        status: 'enabled',
        blockchain_key: 'btc-electrum',
        currency_id: 'btc',
        deposit_enabled: true,
        withdrawal_enabled: true,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0002',
        withdraw_fee: '0.0005',
        min_withdraw_amount: '0.0006',
        base_factor: 100000000,
        explorer_transaction: 'https://www.blockchain.com/btc/tx/#{txid}',
        explorer_address: 'https://www.blockchain.com/btc/address/#{address}',
        description: null,
        warning: null,
        protocol: 'BTC',
        min_confirmations: 3,
      },
    ],
  },
  {
    id: 'eth',
    status: 'enabled',
    name: 'Ethereum',
    description: null,
    options: {},
    homepage: null,
    price: '205429.367850136',
    explorer_transaction: 'https://etherscan.io/tx/#{txid}',
    explorer_address: 'https://etherscan.io/address/#{address}',
    type: 'coin',
    deposit_enabled: true,
    withdrawal_enabled: true,
    deposit_fee: '0.0',
    min_deposit_amount: '0.002',
    withdraw_fee: '0.001',
    min_withdraw_amount: '0.002',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 5,
    position: 4,
    icon_url:
      'https://assets.coingecko.com/coins/images/279/small/ethereum.png?1595348880',
    min_confirmations: 6,
    blockchain_key: 'eth-mainnet',
    networks: [
      {
        id: 12,
        status: 'enabled',
        blockchain_key: 'eth-mainnet',
        currency_id: 'eth',
        deposit_enabled: true,
        withdrawal_enabled: true,
        deposit_fee: '0.0',
        min_deposit_amount: '0.002',
        withdraw_fee: '0.001',
        min_withdraw_amount: '0.002',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://etherscan.io/tx/#{txid}',
        explorer_address: 'https://etherscan.io/address/#{address}',
        description: null,
        warning: null,
        protocol: 'Ethereum (ERC20)',
        min_confirmations: 6,
      },
    ],
  },
  {
    id: 'bnb',
    status: 'enabled',
    name: 'Binance coin',
    description: null,
    options: {
      Comment: '"Disabling as CoinDCX need memo to deposit this BNB"',
    },
    homepage: null,
    price: '29375.4362411375',
    explorer_transaction: 'https://bscscan.com/tx/#{txid}',
    explorer_address: 'https://bscscan.com/address/#{address}',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.02',
    withdraw_fee: '0.01',
    min_withdraw_amount: '0.02',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 4,
    position: 5,
    icon_url:
      'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
    min_confirmations: 12,
    blockchain_key: 'bsc',
    networks: [
      {
        id: 6,
        status: 'enabled',
        blockchain_key: 'bsc',
        currency_id: 'bnb',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.02',
        withdraw_fee: '0.01',
        min_withdraw_amount: '0.02',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://bscscan.com/tx/#{txid}',
        explorer_address: 'https://bscscan.com/address/#{address}',
        description: null,
        warning: null,
        protocol: 'BSC',
        min_confirmations: 12,
      },
    ],
  },
  {
    id: 'ltc',
    status: 'enabled',
    name: 'Litecoin',
    description: null,
    options: {},
    homepage: null,
    price: '8083.4641844002',
    explorer_transaction: 'https://blockchair.com/litecoin/transaction/#{txid}',
    explorer_address: 'https://blockchair.com/litecoin/address/#{address}',
    type: 'coin',
    deposit_enabled: true,
    withdrawal_enabled: true,
    deposit_fee: '0.0',
    min_deposit_amount: '0.001',
    withdraw_fee: '0.05',
    min_withdraw_amount: '0.06',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 100000000,
    precision: 4,
    position: 6,
    icon_url:
      'https://assets.coingecko.com/coins/images/2/small/litecoin.png?1547033580',
    min_confirmations: 12,
    blockchain_key: 'ltc-electrum',
    networks: [
      {
        id: 18,
        status: 'enabled',
        blockchain_key: 'ltc-electrum',
        currency_id: 'ltc',
        deposit_enabled: true,
        withdrawal_enabled: true,
        deposit_fee: '0.0',
        min_deposit_amount: '0.001',
        withdraw_fee: '0.05',
        min_withdraw_amount: '0.06',
        base_factor: 100000000,
        explorer_transaction:
          'https://blockchair.com/litecoin/transaction/#{txid}',
        explorer_address: 'https://blockchair.com/litecoin/address/#{address}',
        description: null,
        warning: null,
        protocol: 'LTC',
        min_confirmations: 12,
      },
    ],
  },
  {
    id: 'sol',
    status: 'enabled',
    name: 'Solana',
    description: null,
    options: {},
    homepage: null,
    price: '6525.43231361519',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 4,
    position: 7,
    icon_url:
      'https://assets.coingecko.com/coins/images/4128/small/coinmarketcap-solana-200.png?1616489452',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 25,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'sol',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'shib',
    status: 'enabled',
    name: 'Shiba Inu',
    description: null,
    options: {},
    homepage: null,
    price: '0.0017885706973732',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 0,
    position: 8,
    icon_url:
      'https://assets.coingecko.com/coins/images/11939/small/shiba.png?1622619446',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 24,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'shib',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'doge',
    status: 'enabled',
    name: 'Dogecoin',
    description: null,
    options: {},
    homepage: null,
    price: '9.23605206982101',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 100000000,
    precision: 1,
    position: 9,
    icon_url:
      'https://assets.coingecko.com/coins/images/5/small/dogecoin.png?1547792256',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 10,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'doge',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 100000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'ada',
    status: 'enabled',
    name: 'Cardano',
    description: null,
    options: {},
    homepage: null,
    price: '63.6693019475627',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 3,
    position: 10,
    icon_url:
      'https://assets.coingecko.com/coins/images/975/small/cardano.png?1547034860',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 1,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'ada',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'bch',
    status: 'enabled',
    name: 'BitcoinCash',
    description: null,
    options: {},
    homepage: null,
    price: '22747.5060449615',
    explorer_transaction: 'https://explorer.bitcoin.com/bch/tx/#{txid}',
    explorer_address: 'https://explorer.bitcoin.com/bch/address/#{address}',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0001',
    withdraw_fee: '0.00001',
    min_withdraw_amount: '0.0001',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 100000000,
    precision: 4,
    position: 11,
    icon_url:
      'https://assets.coingecko.com/coins/images/780/small/bitcoin-cash-circle.png?1594689492',
    min_confirmations: 3,
    blockchain_key: 'bitgo-bch',
    networks: [
      {
        id: 5,
        status: 'enabled',
        blockchain_key: 'bitgo-bch',
        currency_id: 'bch',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0001',
        withdraw_fee: '0.00001',
        min_withdraw_amount: '0.0001',
        base_factor: 100000000,
        explorer_transaction: 'https://explorer.bitcoin.com/bch/tx/#{txid}',
        explorer_address: 'https://explorer.bitcoin.com/bch/address/#{address}',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 3,
      },
    ],
  },
  {
    id: 'xrp',
    status: 'enabled',
    name: 'Ripple',
    description: null,
    options: {},
    homepage: null,
    price: '58.3400396426371',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000,
    precision: 2,
    position: 13,
    icon_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/52.png',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 31,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'xrp',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'trx',
    status: 'enabled',
    name: 'Tron',
    description: null,
    options: {},
    homepage: null,
    price: '4.71563095063395',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000,
    precision: 0,
    position: 14,
    icon_url:
      'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png?1547035066',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 27,
        status: 'enabled',
        blockchain_key: 'tron-mainnet',
        currency_id: 'trx',
        deposit_enabled: true,
        withdrawal_enabled: true,
        deposit_fee: '0.0',
        min_deposit_amount: '4.0',
        withdraw_fee: '3.0',
        min_withdraw_amount: '5.0',
        base_factor: 1000000,
        explorer_transaction: 'https://tronscan.org/#/transaction/#{txid}',
        explorer_address: 'https://tronscan.org/#/address/#{address}',
        description: '',
        warning: '',
        protocol: 'Tron (TRC20)',
        min_confirmations: 30,
      },
    ],
  },
  {
    id: 'dot',
    status: 'enabled',
    name: 'Polkadot',
    description: null,
    options: {},
    homepage: null,
    price: '1360.38951452284',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 3,
    position: 15,
    icon_url:
      'https://assets.coingecko.com/coins/images/12171/small/aJGBjJFU_400x400.jpg?1597804776',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 11,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'dot',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'luna',
    status: 'enabled',
    name: 'Terra',
    description: null,
    options: {},
    homepage: null,
    price: '7805.4837265853',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 3,
    position: 16,
    icon_url:
      'https://assets.coingecko.com/coins/images/8284/small/luna1557227471663.png?1567147072',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 19,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'luna',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'xlm',
    status: 'enabled',
    name: 'Steller',
    description: null,
    options: {},
    homepage: null,
    price: '14.0126692268305',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 10000000,
    precision: 2,
    position: 17,
    icon_url:
      'https://assets.coingecko.com/coins/images/100/small/Stellar_symbol_black_RGB.png?1552356157',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 30,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'xlm',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 10000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'busd',
    status: 'enabled',
    name: 'Binance USD',
    description: null,
    options: {},
    homepage: null,
    price: '78.7711133607796',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 2,
    position: 18,
    icon_url:
      'https://assets.coingecko.com/coins/images/9576/small/BUSD.png?1568947766',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 8,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'busd',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'uni',
    status: 'enabled',
    name: 'Uniswap (ERC20)',
    description: null,
    options: {},
    homepage: null,
    price: '689.836102922732',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 3,
    position: 19,
    icon_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 28,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'uni',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'matic',
    status: 'enabled',
    name: 'Matic Token',
    description: null,
    options: {},
    homepage: null,
    price: '113.544236345288',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 2,
    position: 20,
    icon_url:
      'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0/logo.png',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 21,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'matic',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'ftt',
    status: 'enabled',
    name: 'FTX Token',
    description: null,
    options: {},
    homepage: null,
    price: '3224.08405351905',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 4,
    position: 21,
    icon_url:
      'https://assets.coingecko.com/coins/images/9026/small/F.png?1609051564',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 14,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'ftt',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'avax',
    status: 'enabled',
    name: 'Avalanche',
    description: null,
    options: {},
    homepage: null,
    price: '5859.95453648335',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 8,
    position: 22,
    icon_url:
      'https://assets.coingecko.com/coins/images/12559/small/coin-round-red.png?1604021818',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 4,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'avax',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'near',
    status: 'enabled',
    name: 'Near',
    description: null,
    options: {},
    homepage: null,
    price: '853.688237388725',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 8,
    position: 23,
    icon_url:
      'https://assets.coingecko.com/coins/images/10365/small/near_icon.png?1601359077',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 22,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'near',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'link',
    status: 'enabled',
    name: 'ChainLink Token',
    description: null,
    options: {},
    homepage: null,
    price: '1045.46802246145',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 8,
    position: 24,
    icon_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1975.png',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 17,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'link',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'algo',
    status: 'enabled',
    name: 'Algorand',
    description: null,
    options: {},
    homepage: null,
    price: '57.5673934498905',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 8,
    position: 25,
    icon_url:
      'https://assets.coingecko.com/coins/images/4380/small/download.png?1547039725',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 2,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'algo',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'atom',
    status: 'enabled',
    name: 'Cosmos',
    description: null,
    options: {},
    homepage: null,
    price: '2214.60616819054',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 8,
    position: 26,
    icon_url:
      'https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png?1555657960',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 3,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'atom',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'ftm',
    status: 'enabled',
    name: 'Fantom',
    description: null,
    options: {},
    homepage: null,
    price: '97.2598050768287',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 8,
    position: 27,
    icon_url:
      'https://assets.coingecko.com/coins/images/4001/small/Fantom.png?1558015016',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 13,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'ftm',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'sand',
    status: 'enabled',
    name: 'Sandbox',
    description: null,
    options: {},
    homepage: null,
    price: '222.605021425791',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 8,
    position: 28,
    icon_url:
      'https://assets.coingecko.com/coins/images/12129/small/sandbox_logo.jpg?1597397942',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 23,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'sand',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'mana',
    status: 'enabled',
    name: 'Decentraland',
    description: null,
    options: {},
    homepage: null,
    price: '187.4148634354',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 8,
    position: 29,
    icon_url:
      'https://assets.coingecko.com/coins/images/878/small/decentraland-mana.png?1550108745',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 20,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'mana',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'sushi',
    status: 'enabled',
    name: 'SushiSwap',
    description: null,
    options: {},
    homepage: null,
    price: '233.499855451866',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 1000000000000000000,
    precision: 8,
    position: 30,
    icon_url:
      'https://assets.coingecko.com/coins/images/12271/small/512x512_Logo_no_chop.png?1606986688',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 26,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'sushi',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 1000000000000000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
  {
    id: 'gala',
    status: 'enabled',
    name: 'Gala',
    description: null,
    options: {},
    homepage: null,
    price: '17.1303390993566',
    explorer_transaction: 'https://coindhan.com/',
    explorer_address: 'https://coindhan.com/',
    type: 'coin',
    deposit_enabled: false,
    withdrawal_enabled: false,
    deposit_fee: '0.0',
    min_deposit_amount: '0.0',
    withdraw_fee: '0.0',
    min_withdraw_amount: '0.0',
    withdraw_limit_24h: '0.0',
    withdraw_limit_72h: '0.0',
    base_factor: 100000000,
    precision: 8,
    position: 31,
    icon_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/7080.png',
    min_confirmations: 1,
    blockchain_key: 'lightning blockchain',
    networks: [
      {
        id: 15,
        status: 'enabled',
        blockchain_key: 'lightning blockchain',
        currency_id: 'gala',
        deposit_enabled: false,
        withdrawal_enabled: false,
        deposit_fee: '0.0',
        min_deposit_amount: '0.0',
        withdraw_fee: '0.0',
        min_withdraw_amount: '0.0',
        base_factor: 100000000,
        explorer_transaction: 'https://coindhan.com/',
        explorer_address: 'https://coindhan.com/',
        description: null,
        warning: null,
        protocol: null,
        min_confirmations: 1,
      },
    ],
  },
];

export const columnsMarket = [
  {
    title: 'Markets',
    dataIndex: 'name',
    filters: [
      {
        text: 'btc',
        value: 'BTC',
      },
    ],

    filterSearch: true,
    onFilterSearch: (input, record) => record.name.includes(input),
  },
  {
    title: 'Min. Order Size',
    dataIndex: 'min_amount',
    sorter: (a, b) => a.min_amount - b.min_amount,
  },
  {
    title: 'Maker Fee',
    dataIndex: 'maker',
  },
  {
    title: 'Taker Fee',
    dataIndex: 'taker',
  },
  {
    title: 'status',
    dataIndex: 'state',
    render: (text) => (
      <p style={{ color: text.includes('enabled') ? 'green' : 'black' }}>
        {text}
      </p>
    ),
  },
];

export const columnsFees = [
  {
    title: 'Name',
    dataIndex: 'name',

    filterSearch: true,
    onFilterSearch: (input, record) => record.name.includes(input),
    width: '30%',
  },
  {
    title: 'Withdraw fee',
    dataIndex: 'withdraw_fee',
    sorter: (a, b) => a.withdraw_fee - b.withdraw_fee,
  },
  {
    title: 'Min. Deposit Amt.',
    dataIndex: 'min_deposit_amount',
  },
  {
    title: 'Min. Withraw Amt.',
    dataIndex: 'min_wihtdraw_amount',
  },
  {
    title: 'conformations',
    dataIndex: 'min_confirmations',
  },
];
